<?php

/**
 * @file
 * Provides a formation4 entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function formation4_theme() {
  return [
    'formation4' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for formation4 templates.
 *
 * Default template: formation4.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the formation4 information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_formation4(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
