<?php

/**
 * @file
 * Provides a formation3 entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function formation3_theme() {
  return [
    'formation3' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for formation3 templates.
 *
 * Default template: formation3.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the formation3 information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_formation3(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
