formation4.formation4_type.*:
  type: config_entity
  label: 'formation4 type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
